apiVersion: v1
kind: Service
metadata:
  name: libraryhub-service
spec:
  selector:
    app: libraryhub
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  type: NodePort
